### ISSUE TITLE
Filter by comment not working as expected

### ISSUE THREAD

**Issue by MaxMatti** [hicknhack-software/redmine_hourglass#102]
I am experiencing weird behaviour when filtering my time recordings by comment:

I have 4 time recordings for this week:
Day 1: A, B
Day 2: C, D
recording D has the comment "Fehlbuchung" and was created, when I booked only a part of C.
recordings A, B and C have been booked.

When I filter my recordings so that only mine from this week are shown, all 4 appear, as expected.
When I add a filter to only show recordings where the comment contains "Fehlbuchung", only D appears, as expected.
When I set the filter to _not_ show recordings where the comment contains "Fehlbuchung", only recording C is shown. Recordings A and B are not shown, even though I would not expect them to be shown.
When I set the filter to show only recordings that do not have a comment, recordings A, B and C are shown, as expected.
When I set the filter to show only recordings that do have a comment, recordings C and D are shown, even though I would not expect recording C here.

**Comment by arBmind** [comment]
@MaxMatti Thank you for the detailed bug report. We will try it and fix it as soon as possible.

**Comment by MaxMatti** [comment]
The bug still exists in the newer version. Please reopen.

**Comment by arBmind** [comment]
I tested the same scenarios with Issue topics. It delivers the same unwanted behaviour.

This behaviour is nothing we from hourglass. It's a default behaviour of Redmine and should be changed there, if a change is required.
