### ISSUE TITLE
Ticket suggestions to book current recording do not work

### ISSUE THREAD

**Issue by MaxMatti** [hicknhack-software/redmine_hourglass#106]
To reproduce:
* start time tracking
* enter search term in ticket field of current time recording

Expected result:
* suggestions for tickets show up below the input field

Actual result:
* nothing happens

Notes:
* when opening the menu to book a previously created recording this bug is fixed, even after closing that menu again

**Comment by arBmind** [comment]
This behavior occurs if the input was used without being focused before. (Sometimes it is focused by default)
