### ISSUE TITLE
Regression: Automatic Project Selection Doesn’t Work on Booking

### ISSUE THREAD

**Issue by rbugajewski** [hicknhack-software/redmine_hourglass#127]
Recently I updated our Redmine installation & this plugin.

In older versions the project was automatically selected when you booked a time log from the “Overview” page just by entering the issue ID and selecting the proposed menu item.

With the most recent version you have to select a project first, then enter the issue ID. If you enter the issue ID first, then try to select the project, it simply doesn’t work.

We usually have logs from a couple of days before we book them. Every day has also multiple logs, so booking is a lot more work and less straightforward for us with the current version.

**Comment by thomst** [comment]
Same issue for us. Selecting an issue on the Overview-page does not update the procect-field - using hourglass 1.1.2.

**Comment by arBmind** [comment]
The jquery query was no longer valid. Fixed with #146
