### ISSUE TITLE
Stop-&-New-button not working

### ISSUE THREAD

**Issue by thomst** [hicknhack-software/redmine_hourglass#128]
After a redmine-migration we've got some problems:

- Stop-&-New only stops the time-tracking but does not start a new.
- Editing the end-time of an already saved timebooking does not work.

While the redmine-migration we switched from ruby 2.3 to 2.4. Are there any known incompatibilities?

**Comment by RolandSM** [comment]
I installed it without any errors on redmine 4.0.4 but I cannot see any start-/stop-button?
The general entry time measurement is available in top main menu but not start stop on the right of my user?
I also activated it in my rules and in the projects like described?

**Comment by thomst** [comment]
This issue vanished for me with an update to version 1.1.1.
(Sorry I didn't tried that before...)
