### ISSUE TITLE
NoMethodError: undefined method `active_record'

### ISSUE THREAD

**Issue by matheus-souza** [hicknhack-software/redmine_hourglass#133]
When I install the plugin I get this error when running `bundle exec rake redmine:plugins:migrate RAILS_ENV=production` in the plugin folder as shown below:

```
root@a0cd7de48c94:/home/redmine/redmine/plugins/redmine_hourglass# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /home/redmine/redmine)rake aborted!
NoMethodError: undefined method `active_record' for #<Rails::Application::Configuration:0x0000000002cabde8>
/var/lib/gems/2.4.0/gems/railties-5.2.4.1/lib/rails/railtie/configuration.rb:97:in `method_missing'/home/redmine/redmine/config/application.rb:20:in `<class:Application>'
/home/redmine/redmine/config/application.rb:8:in `<module:RedmineApp>'
/home/redmine/redmine/config/application.rb:7:in `<top (required)>'
/home/redmine/redmine/Rakefile:5:in `require'
/home/redmine/redmine/Rakefile:5:in `<top (required)>'
/var/lib/gems/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'(See full trace by running task with --trace)
```

![image](https://user-images.githubusercontent.com/14989876/72452896-0d415500-379d-11ea-8326-f38091cae128.png)

**Comment by arBmind** [comment]
It seems you are executing the command in the wrong directory.

**Comment by matheus-souza** [comment]
@arBmind Which directory should it run `bundle exec rake redmine:plugins:migrate RAILS_ENV=production`? At the root of the Redmine installation or at the root of the plugin?

**Comment by arBmind** [comment]
@matheus-souza Your assessment is correct. From the screenshot you seem to already have tried one of the options. I would suggest to try the other one.

You run `redmine:plugins:migrate`. This task is a Redmine task that asks each installed plugin for necessary migrations and executes them.

**Comment by matheus-souza** [comment]
Explicit command execution directory in #134
