### ISSUE TITLE
Error stopping time recording

### ISSUE THREAD

**Issue by matheus-souza** [hicknhack-software/redmine_hourglass#135]
When stopping the time stamp, this error appears in the request. I don't know how to fix it and there is nothing in the documentation to clarify my problem. I would like help to resolve this inconvenience.

Attached image with error:

Response:
```
{"message":"Atividade não pode ficar vazio","status":400}
```

![image](https://user-images.githubusercontent.com/14989876/72901675-efc63b00-3d08-11ea-8d0a-eb84e23fd42e.png)

![image](https://user-images.githubusercontent.com/14989876/72901774-1dab7f80-3d09-11ea-9021-01f84c775df7.png)

**Comment by arBmind** [comment]
I cannot reproduce this. It's a central functionality of the plugin. For most users this seems to work.

Without further details, I have no way to inspect this.
