### ISSUE TITLE
Error in bundle when installing redmine_hourglass plugin

### ISSUE THREAD

**Issue by fjllacer** [hicknhack-software/redmine_hourglass#136]
I am trying to install the hourglass plugin in my Bitnami Redmine stack:

  Redmine version                3.3.2.stable
  Ruby version                   2.1.10-p492 (2016-04-01) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2

I downloaded the last version of the plugin: 1.1.2 and extracted inside my plugins folder:

/opt/redmine/apps/redmine/htdocs/plugins/redmine_hourglass

Then i I try to bundle giving these commands:

# /opt/redmine/use_redmine   ( to set the Redmine environment and paths)
# cd /opt/redmine/apps/redmine/htdocs/plugins/redmine_hourglass
# bundle install

Here is the output:
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this
application for all non-root users on this machine.
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Installing rake 13.0.1

Gem::InstallError: rake requires Ruby version >= 2.2.
An error occurred while installing rake (13.0.1), and Bundler cannot continue.
Make sure that `gem install rake -v '13.0.1'` succeeds before bundling.

The plugin requirements say my Redmine stack versions are compatible. Then, why is it requiring this gem version ? My ruby version is 2.1 and I can see I already have rake 12.0 installed. 
How can I solve this ?

Regards

**Comment by arBmind** [comment]
Sorry, but this is not a hourglass related issue. Ruby 2.1 is too old now and no longer supported. You are also running `bundle install` from the wrong directory.
