### ISSUE TITLE
Redmine 4.1.1 and Ruby 2.6.6 dependency errors

### ISSUE THREAD

**Issue by RolandSM** [hicknhack-software/redmine_hourglass#139]
Hello,

I followed your description but on "bundle install" I get:

`Bundler could not find compatible versions for gem "i18n":`
`In snapshot (Gemfile.lock):`
`i18n (= 1.6.0)`
`In Gemfile:`
`i18n (~> 1.6.0)`
`faker (= 1.7.3) was resolved to 1.7.3, which depends on`
`i18n (~> 0.5)`
`Running "bundle update" will rebuild your snapshot from scratch, using only`
`the gems in your Gemfile, which may resolve the conflict.`

**Comment by codeyourdream** [comment]
Same error on Ruby 2.5.5
