### ISSUE TITLE
Inline adding or editing timebookings or -entries failes after Redmine update to 4.0.8

### ISSUE THREAD

**Issue by thomst** [hicknhack-software/redmine_hourglass#145]
After a redmine update from 4.0.7 to 4.0.8 adding or editing timebookings via inline form in the table listings fails.
Our specs are as follows:

- Redmine version                4.0.8.stable
- Ruby version                   2.4.6-p354 (2019-04-01) [x86_64-linux]
- redmine_hourglass              1.1.1

When editing an existing entry, this is what happens:

1. An ajax request loads the update form.
2. The row of the entry get hidden.
2. A second row for the form is added.
3. But the ajax response is not inserted. The row simply keeps empty except of tow td elements.

Please help. This is urgent.

**Comment by thomst** [comment]
I've added a debug statement into the `showInlineForm ` function of the [lists.coffee:56](https://github.com/hicknhack-software/redmine_hourglass/blob/87bf6e73f04a6b83d12a0642c58c0761be6f3008/app/assets/javascripts/lists.coffee#L56) Skript:

```
showInlineForm = (event, response) ->
  console.log response
...
```
The output in the debug console of the browser is `undefined`

**Comment by jensschuppe** [comment]
[This](https://edgeguides.rubyonrails.org/working_with_javascript_in_rails.html#rails-ujs-event-handlers) might be worth a read and explains why the response attribute is `undefined`:

> Rails 5.1 introduced rails-ujs and dropped jQuery as a dependency. As a result the Unobtrusive JavaScript (UJS) driver has been rewritten to operate without jQuery. These introductions cause small changes to custom events fired during the request:

> Signature of calls to UJS's event handlers has changed. Unlike the version with jQuery, all custom events return only one parameter: event. In this parameter, there is an additional attribute detail which contains an array of extra parameters.

**Comment by thomst** [comment]
The problem results from un updated js-library:
While redmine-4.0.7 uses jquery-1.11.1-ui-1.11.0-ujs-4.3.1.js, redmine4.0.8 uses jquery-1.11.1-ui-1.11.0-ujs-5.2.4.5.js.
The hourglass-javascript is not compatible with the updated js-lib.
The signature of the ajax success call seems to differ in the new version of this library.

**Comment by jensschuppe** [comment]
This seems to have been fixed already on the `develop` branch in #141 with 2ccdb452f5159c34311ad4e604822a17465d4d77.

**Comment by thomst** [comment]
> This seems to have been fixed already on the `develop` branch in #141 with [2ccdb45](https://github.com/hicknhack-software/redmine_hourglass/commit/2ccdb452f5159c34311ad4e604822a17465d4d77).

This commit was developed for the v1.1.2 which dropped the support for redmine 4.0.x.
I tried to patch our 1.1.1 hourglass with [2ccdb45](https://github.com/hicknhack-software/redmine_hourglass/commit/2ccdb452f5159c34311ad4e604822a17465d4d77). Unfortunatly that leads to another error. Probably because redmine-4.1.x uses even another version of the js-lib above (The UI-Part seemed to be updated.)

**Comment by thomst** [comment]
I modified the patch from [2ccdb45](https://github.com/hicknhack-software/redmine_hourglass/commit/2ccdb452f5159c34311ad4e604822a17465d4d77). Instead of `event.detail` I needed to use `event.originalEvent.detail`. This seems to work.
[hourglass-145.txt](https://github.com/hicknhack-software/redmine_hourglass/files/6632252/hourglass-145.txt)

**Comment by arBmind** [comment]
Fixed on develop
