### ISSUE TITLE
Error installing in redmine docker - Could not find a JavaScript runtime

### ISSUE THREAD

**Issue by EnricoBeltramo** [hicknhack-software/redmine_hourglass#147]
I tried to use the plugin inside a redmine docker
so:
- copied files in plugins folder
- from /usr/src/redmine of docker I did (libraries necessary to compile all modules):
- apt-get update && apt-get apt-get install build-essential default-libmysqlclient-dev libpq-dev libmagickwand-dev
- bundle update
- bundle exec rake redmine:plugins NAME=redmine_hourglass RAILS_ENV=production

But I get this error:
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
/usr/local/bundle/gems/execjs-2.8.1/lib/execjs/runtimes.rb:58:in `autodetect'
/usr/local/bundle/gems/execjs-2.8.1/lib/execjs.rb:5:in `<module:ExecJS>'
/usr/local/bundle/gems/execjs-2.8.1/lib/execjs.rb:4:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/uglifier-4.2.0/lib/uglifier.rb:5:in `<top (required)>'
/usr/src/redmine/config/application.rb:18:in `<top (required)>'
/usr/src/redmine/Rakefile:5:in `require'
/usr/src/redmine/Rakefile:5:in `<top (required)>'
/usr/local/bundle/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)

**Comment by arBmind** [comment]
Hi @EnricoBeltramo, first - thank you for trying Redmine Hourglass.

You forgot to install an execjs environment. See the 3rd point in the requirements. https://github.com/hicknhack-software/redmine_hourglass#requirements

I hope this resolves your error, otherwise feel free to open an issue again. If you have a suggestion on how to improve the documentation to prevent such errors please suggest some changes as PR.
