### ISSUE TITLE
Unable to load application: NameError: uninitialized constant Hourglass::AlreadyBookedException

### ISSUE THREAD

**Issue by gsdefender** [hicknhack-software/redmine_hourglass#150]
After updating Redmine to latest 4.2.2 and redmine_hourglass to latest git, had the aforementioned error.

I'm attaching the full traceback:
[traceback.txt](https://github.com/hicknhack-software/redmine_hourglass/files/7067528/traceback.txt)

I commented out api_base_controller.rb:13 and then puma could start.

**Comment by arBmind** [comment]
@gsdefender Thanks for reporting the issue.

It seems that the Exception is defined as side effect to loading TimeLog. Therefore Rails cannot find it on demand. So far it seemed to work for us. But it's fragile, therefore I fixed it on develop.
