### ISSUE TITLE
Tab sleeps prevents timer from running

### ISSUE THREAD

**Issue by ckieschnick** [hicknhack-software/redmine_hourglass#152]
Leaving the page open but in background (i.e. inactive tab, inactive browser window) will stop the timer for increasing the time of the current time measurement. A simple fix would be to store the start time and with each ui update calculate the difference (this may lead to funny behavior on changing the clock time). Maybe there is some other way to be notified by the browser when the tab is reactivated so that the timer may continue (or fetch the "real" time from the server).

**Comment by arBmind** [comment]
Was fixed a long time ago…
