### ISSUE TITLE
Compatibility with Redmine 5 ?

### ISSUE THREAD

**Issue by WebPam** [hicknhack-software/redmine_hourglass#155]
I've tried to install the plugin with Redmine 5, but I have the following error :
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

Is redmine_hourglass suposed to work with Redmine 5? 
Thank's a lot for all your work !
All the best
Laurent

**Comment by arBmind** [comment]
So far we have no official support for Redmine 5. It seems some fixes are necessary to support the new version.
Sooner or later we will get around to update the plugin.

**Comment by localhorst** [comment]
I am very interested in this, but unfortunately I have no experience in Ruby programming.

**Comment by arBmind** [comment]
Merged into develop branch.
