### ISSUE TITLE
New issue notification html is escaped

### ISSUE THREAD

**Issue by philhq** [hicknhack-software/redmine_hourglass#19]
Since installing the plugin, every time we create new issue it seems the html is expired on the notification.

![feature__113988](https://cloud.githubusercontent.com/assets/22561/26566423/11cd9a38-44c1-11e7-8124-e1f4b388fa15.png)

**Comment by arBmind** [comment]
I get the issue on every notification.

![image](https://cloud.githubusercontent.com/assets/44107/26578566/a75b5350-4530-11e7-8eab-7ccf1cf9985f.png)

**Comment by philhq** [comment]
The point is the plugins escape the notifications (new issue or users). I disabled the plugin and its back to normal.
![screen shot 2017-05-30 at 9 17 07 am](https://cloud.githubusercontent.com/assets/22561/26584984/c6044d74-4518-11e7-9079-0f914f4b207b.png)

**Comment by jume-dev** [comment]
Strange one, i'll take a look.

**Comment by philhq** [comment]
It is fixed now! abe2fe1 fixed it. Somehow I had to issue a hard restart to nginx for the changes to take effet.

**Comment by jume-dev** [comment]
alright, yeah, saw it now. @arBmind was faster than me :)
