### ISSUE TITLE
Error with https://bitbucket.org/dkuk/a_common_libs and http://rmplus.pro/en/redmine/plugins/user_mentions

### ISSUE THREAD

**Issue by monstrfolk** [hicknhack-software/redmine_hourglass#26]
Everything works after I uninstall this plugin.

Started GET "/settings/plugin/rm_user_mentions" for 67.188.13.138 at 2017-06-01 04:13:31 -0400
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"rm_user_mentions"}
  Current user: XXXXX (id=6)
Completed 500 Internal Server Error in 23ms (ActiveRecord: 5.1ms)

SystemStackError (stack level too deep):
  plugins/a_common_libs/lib/acl/patches/controllers/settings_controller_patch.rb:19:in `plugin_with_a_common_libs'
  plugins/redmine_hourglass/lib/hourglass/redmine_patches/settings_controller_patch.rb:11:in `plugin'
  plugins/a_common_libs/lib/acl/patches/controllers/settings_controller_patch.rb:24:in `plugin_with_a_common_libs'
  plugins/redmine_hourglass/lib/hourglass/redmine_patches/settings_controller_patch.rb:11:in `plugin'
  plugins/a_common_libs/lib/acl/patches/controllers/settings_controller_patch.rb:24:in `plugin_with_a_common_libs'
  plugins/redmine_hourglass/lib/hourglass/redmine_patches/settings_controller_patch.rb:11:in `plugin'
  plugins/a_common_libs/lib/acl/patches/controllers/settings_controller_patch.rb:24:in `plugin_with_a_common_libs'
  plugins/redmine_hourglass/lib/hourglass/redmine_patches/settings_controller_patch.rb:11:in `plugin'
  plugins/a_common_libs/lib/acl/patches/controllers/settings_controller_patch.rb:24:in `plugin_with_a_common_libs'
  plugins/redmine_hourglass/lib/hourglass/redmine_patches/settings_controller_patch.rb:11:in `plugin'
  plugins/a_common_libs/lib/acl/patches/controllers/settings_controller_patch.rb:24:in `plugin_with_a_common_libs'
  plugins/redmine_hourglass/lib/hourglass/redmine_patches/settings_controller_patch.rb:11:in `plugin'
  plugins/a_common_libs/lib/acl/patches/controllers/settings_controller_patch.rb:24:in `plugin_with_a_common_libs'
  plugins/redmine_hourglass/lib/hourglass/redmine_patches/settings_controller_patch.rb:11:in `plugin'
  plugins/a_common_libs/lib/acl/patches/controllers/settings_controller_patch.rb:24:in `plugin_with_a_common_libs'
  plugins/redmine_hourglass/lib/hourglass/redmine_patches/settings_controller_patch.rb:11:in `plugin'
  plugins/a_common_libs/lib/acl/patches/controllers/settings_controller_patch.rb:24:in `plugin_with_a_common_libs'

**Comment by jume-dev** [comment]
Yeah, i think i know what's the problem, gonna fix it
