### ISSUE TITLE
Readd "Continue" aka starting a timer with the same issue and project as another one

### ISSUE THREAD

**Issue by jume-dev** [hicknhack-software/redmine_hourglass#3]
This feature was in the old time tracker but was kinda buggy (hicknhack-software/redmine_time_tracker#195).

If enough people want this back, we may add it again. But we definitly should be careful about the problems mentioned in the linked issue.

**Comment by jume-dev** [comment]
Consider using the suggested icon from here: hicknhack-software/redmine_time_tracker#146

**Comment by arBmind** [comment]
This is working already.
