### ISSUE TITLE
Integration Specs don't report error logs if a 500 occured

### ISSUE THREAD

**Issue by jume-dev** [hicknhack-software/redmine_hourglass#43]
See for example this [travis build](https://travis-ci.org/hicknhack-software/redmine_hourglass/jobs/255238524)

I suspect it's a problem with a method, which is not available in the earlier version of redmine, but actually i have no fucking clue, what went wrong, so i need to setup a redmine 3.2.7 and debug it to see what's the problem.

But be way easier if the cause of the 500 error was accessable somehow.

**Comment by arBmind** [comment]
seems to work… no errors on travis.
