### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by Slavenin** [hicknhack-software/redmine_hourglass#45]
Hi! 
When i click `Stop time tracker ` in issue i see infinity loader. If open chrome dev tools i see:
![2017-08-03_12-55-46](https://user-images.githubusercontent.com/4180077/28916487-0b7432b0-784b-11e7-8675-da27a018f4e0.png)
Redmine 3.3.3.0

**Comment by jume-dev** [comment]
Please provide more informations, like permissions and stuff, but i wonder. Maybe something wrong with your apache?

**Comment by Slavenin** [comment]
> root@63851:~# lsb_release -a
> LSB Version:    core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04.2 LTS
> Release:        16.04
> Codename:       xenial

redmine 3.3.3-0 from bitnami stack

What other information is needed?

**Comment by jume-dev** [comment]
What permissions does your user have? 
Do you have access to the apache server? please check if this does disableing put method anyhow.

**Comment by Slavenin** [comment]
I have root access. But a can not find disableing put method in config.
I find `#LoadModule allowmethods_module modules/mod_allowmethods.so` in `httpd.conf`, but this row commented.

**Comment by jume-dev** [comment]
try searching for the Allow Header but other than that i can't help you, i am not that experienced with server configuring
maybe @arBmind has an idea?

**Comment by arBmind** [comment]
Does this help?
* https://stackoverflow.com/questions/1402229/why-does-my-web-server-software-disallow-put-and-delete-requests
* https://stackoverflow.com/questions/37484888/enable-put-and-delete-methods-on-apache-2-4
