### ISSUE TITLE
400 Bad Request (Note: custom field with type list not rendering)

### ISSUE THREAD

**Issue by Ying666** [hicknhack-software/redmine_hourglass#46]
I think this is not an issue with the plugin itself, but maybe an compatibility issue with one of our other plugins, misconfiguration or else.
Hopefully someone can help me.

If I try to stop the timetracking this error shows up:
> Time entry base Status cannot be blank
Log:
> Started DELETE "/hourglass/time_trackers/8/stop" for 80.156.16.178 at 2017-08-08 15:07:58 +0200
> Processing by Hourglass::TimeTrackersController#stop as JS
>   Parameters: {"id"=>"8"}
>   Current user: XX (id=3)
> Completed 400 Bad Request in 21ms (Views: 0.2ms | ActiveRecord: 3.4ms)

The user/role got all permissions for "Redmine Hourglass (Time Tracker)"
A default value for Activities (time tracking) is set
No subfolder

Systeminformations:
Webserver: nginx + unicorn
> Environment:
>   Redmine version                3.4.2.stable.16831
>   Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
>   Rails version                  4.2.8
>   Environment                    production
>   Database adapter               Mysql2
> SCM:
>   Subversion                     1.9.3
>   Git                            2.7.4
>   Filesystem                     
> Redmine plugins:
>   clipboard_image_paste          1.12
>   disable_activity               0.0.1
>   issue_hot_buttons              0.4.4-burg
>   redmine_agile                  1.4.4
>   redmine_auto_percent           0.0.2
>   redmine_banner                 0.1.2
>   redmine_checklists             3.1.6
>   redmine_contacts               4.1.1
>   redmine_contacts_helpdesk      3.0.8
>   redmine_contacts_invoices      4.1.6
>   redmine_crm_mailchimp          1.0.2
>   redmine_editauthor             0.11.0
>   redmine_favorite_projects      2.0.3
>   redmine_finance                2.1.3
>   redmine_hourglass              1.0.0
>   redmine_lightbox2              0.3.2
>   redmine_local_avatars          0.2.0
>   redmine_people                 1.3.1
>   redmine_products               2.0.4
>   redmine_questions              0.0.7
>   redmine_recenthistory          0.0.2
>   redmine_silencer               0.4.1-burg
>   redmine_wiki_extensions        0.8.0
>   redmine_zenedit                0.0.2
>   sidebar_hide                   0.0.8

**Comment by jume-dev** [comment]
> Time entry base Status cannot be blank
Alright, from the error i guess, you have a custom field Status set for time entries, right? Seems like it is required. Try disableing it for a moment to see if this was the problem.

In any case, there should be a input rendered for this field on the time tracker form.

If this is indeed a custom field, please let me know what you added exactly there

**Comment by Ying666** [comment]
> Alright, from the error i guess, you have a custom field Status set for time entries, right? Seems like it is required. Try disableing it for a moment to see if this was the problem.
If the custom field ist noch required, everything works fine.
Setting a default value and make it required works fine too

> In any case, there should be a input rendered for this field on the time tracker form.
There is a query when stopping the timer, where the user must select an activity.
But no other fields are shown.
> If this is indeed a custom field, please let me know what you added exactly there
The custom field is 
Format: List 
Possible values: 6 Strings
Default value was emtpy until know, to force the user to explicitly set one.
Display: drow-down list

**Comment by jume-dev** [comment]
Alright, seems like the form doesn't properly render the drop down then. I'll take a look into it

**Comment by strfry** [comment]
I can't reproduce the bug on current redmine with only hourglass installed as a plugin.
I tested with a required custom list field of 6 values attached to "Spent Time", and it's rendered fine.
The error message makes sense to me in case it wouldn't be rendered, but i don't see how that could happen.

**Comment by arBmind** [comment]
Ok, seems to work now.
