### ISSUE TITLE
Rake error in Centos

### ISSUE THREAD

**Issue by mauriziotallarico** [hicknhack-software/redmine_hourglass#47]
Hi, i'm getting the following error when trying to rake on RM 3.2.1
Could You pleas help to debug ?
Thanks !
Maurizio

> 
* Process memory map:

00155000-00188000 r-xp 00000000 fd:00 1064654    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/date_core.so
00188000-00189000 rw-p 00032000 fd:00 1064654    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/date_core.so
00189000-0018a000 rw-p 00000000 00:00 0
0018a000-0018b000 r-xp 00000000 fd:00 1064566    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/fcntl.so
0018b000-0018c000 rw-p 00000000 fd:00 1064566    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/fcntl.so
0018c000-001d3000 r-xp 00000000 fd:00 1064644    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/openssl.so
001d3000-001d5000 rw-p 00047000 fd:00 1064644    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/openssl.so
001d5000-00237000 r-xp 00000000 fd:00 547924     /usr/lib/libssl.so.1.0.1e
00237000-0023a000 r--p 00061000 fd:00 547924     /usr/lib/libssl.so.1.0.1e
0023a000-0023e000 rw-p 00064000 fd:00 547924     /usr/lib/libssl.so.1.0.1e
0023e000-0027c000 r-xp 00000000 fd:00 2905107    /lib/libgssapi_krb5.so.2.2
0027c000-0027d000 r--p 0003e000 fd:00 2905107    /lib/libgssapi_krb5.so.2.2
0027d000-0027e000 rw-p 0003f000 fd:00 2905107    /lib/libgssapi_krb5.so.2.2
0027e000-00281000 r-xp 00000000 fd:00 2904344    /lib/libcom_err.so.2.1
00281000-00282000 r--p 00002000 fd:00 2904344    /lib/libcom_err.so.2.1
00282000-00283000 rw-p 00003000 fd:00 2904344    /lib/libcom_err.so.2.1
00283000-002ab000 r-xp 00000000 fd:00 2905175    /lib/libk5crypto.so.3.1
002ab000-002ac000 r--p 00028000 fd:00 2905175    /lib/libk5crypto.so.3.1
002ac000-002ad000 rw-p 00029000 fd:00 2905175    /lib/libk5crypto.so.3.1
002ad000-002ae000 rw-p 00000000 00:00 0
002ae000-002b8000 r-xp 00000000 fd:00 2903590    /lib/libkrb5support.so.0.1
002b8000-002b9000 r--p 00009000 fd:00 2903590    /lib/libkrb5support.so.0.1
002b9000-002ba000 rw-p 0000a000 fd:00 2903590    /lib/libkrb5support.so.0.1
002ba000-002bc000 r-xp 00000000 fd:00 2903597    /lib/libkeyutils.so.1.3
002bc000-002bd000 r--p 00001000 fd:00 2903597    /lib/libkeyutils.so.1.3
002bd000-002be000 rw-p 00002000 fd:00 2903597    /lib/libkeyutils.so.1.3
002be000-002bf000 r-xp 00000000 fd:00 1064562    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/digest/sha1.so
002bf000-002c0000 rw-p 00000000 fd:00 1064562    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/digest/sha1.so
002c0000-002dd000 r-xp 00000000 fd:00 551430     /usr/lib/libyaml-0.so.2.0.2
002dd000-002de000 rw-p 0001d000 fd:00 551430     /usr/lib/libyaml-0.so.2.0.2
002df000-002e0000 r-xp 00000000 00:00 0          [vdso]
002e0000-002e1000 r-xp 00000000 fd:00 1064584    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/utf_16be.so
002e1000-002e2000 rw-p 00000000 fd:00 1064584    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/utf_16be.so
002e2000-002f4000 r-xp 00000000 fd:00 1064650    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/bigdecimal.so
002f4000-002f5000 rw-p 00011000 fd:00 1064650    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/bigdecimal.so
002f5000-002fa000 r-xp 00000000 fd:00 2889658    /usr/local/rvm/gems/ruby-2.1.0/gems/json-1.8.6/lib/json/ext/parser.so
002fa000-002fb000 rw-p 00004000 fd:00 2889658    /usr/local/rvm/gems/ruby-2.1.0/gems/json-1.8.6/lib/json/ext/parser.so
002fb000-002fe000 r-xp 00000000 fd:00 1064571    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/racc/cparse.so
002fe000-002ff000 rw-p 00003000 fd:00 1064571    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/racc/cparse.so
00300000-00307000 r-xp 00000000 fd:00 2905121    /lib/libcrypt-2.12.so
00307000-00308000 r--p 00007000 fd:00 2905121    /lib/libcrypt-2.12.so
00308000-00309000 rw-p 00008000 fd:00 2905121    /lib/libcrypt-2.12.so
00309000-00330000 rw-p 00000000 00:00 0
00330000-00331000 r-xp 00000000 fd:00 1064580    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/iso_8859_1.so
00331000-00332000 rw-p 00000000 fd:00 1064580    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/iso_8859_1.so
00332000-00334000 r-xp 00000000 fd:00 2904333    /lib/libfreebl3.so
00334000-00335000 r--p 00001000 fd:00 2904333    /lib/libfreebl3.so
00335000-00336000 rw-p 00002000 fd:00 2904333    /lib/libfreebl3.so
00336000-0033f000 r-xp 00000000 fd:00 2889657    /usr/local/rvm/gems/ruby-2.1.0/gems/json-1.8.6/lib/json/ext/generator.so
0033f000-00340000 rw-p 00008000 fd:00 2889657    /usr/local/rvm/gems/ruby-2.1.0/gems/json-1.8.6/lib/json/ext/generator.so
00341000-00360000 r-xp 00000000 fd:00 2905150    /lib/ld-2.12.so
00360000-00361000 r--p 0001e000 fd:00 2905150    /lib/ld-2.12.so
00361000-00362000 rw-p 0001f000 fd:00 2905150    /lib/ld-2.12.so
00364000-004f5000 r-xp 00000000 fd:00 2905155    /lib/libc-2.12.so
004f5000-004f7000 r--p 00191000 fd:00 2905155    /lib/libc-2.12.so
004f7000-004f8000 rw-p 00193000 fd:00 2905155    /lib/libc-2.12.so
004f8000-004fb000 rw-p 00000000 00:00 0
004fd000-00514000 r-xp 00000000 fd:00 2890795    /lib/libpthread-2.12.so
00514000-00515000 r--p 00016000 fd:00 2890795    /lib/libpthread-2.12.so
00515000-00516000 rw-p 00017000 fd:00 2890795    /lib/libpthread-2.12.so
00516000-00518000 rw-p 00000000 00:00 0
0051a000-0051d000 r-xp 00000000 fd:00 2905196    /lib/libdl-2.12.so
0051d000-0051e000 r--p 00002000 fd:00 2905196    /lib/libdl-2.12.so
0051e000-0051f000 rw-p 00003000 fd:00 2905196    /lib/libdl-2.12.so
00521000-00549000 r-xp 00000000 fd:00 2905202    /lib/libm-2.12.so
00549000-0054a000 r--p 00027000 fd:00 2905202    /lib/libm-2.12.so
0054a000-0054b000 rw-p 00028000 fd:00 2905202    /lib/libm-2.12.so
0054b000-00552000 r-xp 00000000 fd:00 547982     /usr/lib/libSM.so.6.0.1
00552000-00553000 rw-p 00006000 fd:00 547982     /usr/lib/libSM.so.6.0.1
00553000-0055a000 r-xp 00000000 fd:00 2890718    /lib/librt-2.12.so
0055a000-0055b000 r--p 00006000 fd:00 2890718    /lib/librt-2.12.so
0055b000-0055c000 rw-p 00007000 fd:00 2890718    /lib/librt-2.12.so
0055e000-00570000 r-xp 00000000 fd:00 2890803    /lib/libz.so.1.2.3
00570000-00571000 r--p 00011000 fd:00 2890803    /lib/libz.so.1.2.3
00571000-00572000 rw-p 00012000 fd:00 2890803    /lib/libz.so.1.2.3
00572000-00649000 r-xp 00000000 fd:00 2904312    /lib/libkrb5.so.3.3
00649000-0064f000 r--p 000d6000 fd:00 2904312    /lib/libkrb5.so.3.3
0064f000-00650000 rw-p 000dc000 fd:00 2904312    /lib/libkrb5.so.3.3
00650000-00683000 r-xp 00000000 fd:00 550100     /usr/lib/libfontconfig.so.1.4.4
00683000-00685000 rw-p 00032000 fd:00 550100     /usr/lib/libfontconfig.so.1.4.4
00685000-00687000 r-xp 00000000 fd:00 551258     /usr/lib/libXau.so.6.0.0
00687000-00688000 rw-p 00001000 fd:00 551258     /usr/lib/libXau.so.6.0.0
00689000-0068b000 r-xp 00000000 fd:00 1064569    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/etc.so
0068b000-0068c000 rw-p 00001000 fd:00 1064569    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/etc.so
0068c000-00690000 r-xp 00000000 fd:00 2905062    /lib/libuuid.so.1.3.0
00690000-00691000 rw-p 00003000 fd:00 2905062    /lib/libuuid.so.1.3.0
00693000-006b0000 r-xp 00000000 fd:00 2904302    /lib/libselinux.so.1
006b0000-006b1000 r--p 0001d000 fd:00 2904302    /lib/libselinux.so.1
006b1000-006b2000 rw-p 0001e000 fd:00 2904302    /lib/libselinux.so.1
006b4000-006c9000 r-xp 00000000 fd:00 2904351    /lib/libresolv-2.12.so
006c9000-006cb000 r--p 00015000 fd:00 2904351    /lib/libresolv-2.12.so
006cb000-006cc000 rw-p 00017000 fd:00 2904351    /lib/libresolv-2.12.so
006cc000-006ce000 rw-p 00000000 00:00 0
006ce000-00727000 r-xp 00000000 fd:00 2257841    /usr/local/rvm/gems/ruby-2.1.0/gems/rmagick-2.16.0/lib/RMagick2.so
00727000-00729000 rw-p 00059000 fd:00 2257841    /usr/local/rvm/gems/ruby-2.1.0/gems/rmagick-2.16.0/lib/RMagick2.so
00729000-00740000 r-xp 00000000 fd:00 551199     /usr/lib/libICE.so.6.3.0
00740000-00742000 rw-p 00016000 fd:00 551199     /usr/lib/libICE.so.6.3.0
00742000-00743000 rw-p 00000000 00:00 0
00743000-00746000 r-xp 00000000 fd:00 1064608    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/euc_jp.so
00746000-00747000 rw-p 00002000 fd:00 1064608    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/euc_jp.so
00749000-0074a000 r-xp 00000000 fd:00 1064558    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/digest/md5.so
0074a000-0074b000 rw-p 00000000 fd:00 1064558    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/digest/md5.so
0074b000-0074d000 r-xp 00000000 fd:00 1064582    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/shift_jis.so
0074d000-0074e000 rw-p 00001000 fd:00 1064582    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/shift_jis.so
00751000-00752000 r-xp 00000000 fd:00 1064561    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/digest/sha2.so
00752000-00753000 rw-p 00000000 fd:00 1064561    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/digest/sha2.so
00753000-00756000 r-xp 00000000 fd:00 1064620    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/trans/utf_16_32.so
00756000-00757000 rw-p 00002000 fd:00 1064620    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/trans/utf_16_32.so
0075a000-00771000 r-xp 00000000 fd:00 820422     /usr/lib/gconv/CP932.so
00771000-00772000 r--p 00016000 fd:00 820422     /usr/lib/gconv/CP932.so
00772000-00773000 rw-p 00017000 fd:00 820422     /usr/lib/gconv/CP932.so
00773000-00783000 r-xp 00000000 fd:00 2890794    /lib/libbz2.so.1.0.4
00783000-00784000 rw-p 00010000 fd:00 2890794    /lib/libbz2.so.1.0.4
00784000-0078d000 r-xp 00000000 fd:00 2890133    /usr/local/rvm/gems/ruby-2.1.0/gems/mysql2-0.3.21/lib/mysql2/mysql2.so
0078d000-0078e000 rw-p 00009000 fd:00 2890133    /usr/local/rvm/gems/ruby-2.1.0/gems/mysql2-0.3.21/lib/mysql2/mysql2.so
00799000-0079f000 r-xp 00000000 fd:00 1064567    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/psych.so
0079f000-007a0000 rw-p 00005000 fd:00 1064567    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/psych.so
007a0000-007b6000 r-xp 00000000 fd:00 552847     /usr/lib/libgomp.so.1.0.0
007b6000-007b7000 rw-p 00015000 fd:00 552847     /usr/lib/libgomp.so.1.0.0
007da000-007e0000 r-xp 00000000 fd:00 1064642    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/pathname.so
007e0000-007e1000 rw-p 00006000 fd:00 1064642    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/pathname.so
007e1000-00808000 r-xp 00000000 fd:00 547978     /usr/lib/libxcb.so.1.1.0
00808000-00809000 rw-p 00026000 fd:00 547978     /usr/lib/libxcb.so.1.1.0
00809000-0084a000 r-xp 00000000 fd:00 1064643    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/nkf.so
0084a000-0084e000 rw-p 00041000 fd:00 1064643    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/nkf.so
0084e000-00850000 rw-p 00000000 00:00 0
008d1000-008d2000 r-xp 00000000 fd:00 1064595    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/utf_32le.so
008d2000-008d3000 rw-p 00000000 fd:00 1064595    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/utf_32le.so
008d5000-008e6000 r-xp 00000000 fd:00 548773     /usr/lib/libXext.so.6.4.0
008e6000-008e7000 rw-p 00010000 fd:00 548773     /usr/lib/libXext.so.6.4.0
008e9000-0090f000 r-xp 00000000 fd:00 2904316    /lib/libexpat.so.1.5.2
0090f000-00911000 rw-p 00025000 fd:00 2904316    /lib/libexpat.so.1.5.2
00913000-009a8000 r-xp 00000000 fd:00 550719     /usr/lib/libfreetype.so.6.3.22
009a8000-009ac000 rw-p 00094000 fd:00 550719     /usr/lib/libfreetype.so.6.3.22
009b8000-009b9000 r-xp 00000000 fd:00 1064598    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/utf_32be.so
009b9000-009ba000 rw-p 00000000 fd:00 1064598    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/utf_32be.so
009f6000-009fb000 r-xp 00000000 fd:00 1064638    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/strscan.so
009fb000-009fc000 rw-p 00004000 fd:00 1064638    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/strscan.so
00a08000-00a0a000 r-xp 00000000 fd:00 1064597    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/encdb.so
00a0a000-00a0b000 rw-p 00001000 fd:00 1064597    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/encdb.so
00a0f000-00a2c000 r-xp 00000000 fd:00 2905394    /lib/libgcc_s-4.4.7-20120601.so.1
00a2c000-00a2d000 rw-p 0001d000 fd:00 2905394    /lib/libgcc_s-4.4.7-20120601.so.1
00a65000-00a67000 r-xp 00000000 fd:00 1064652    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/thread.so
00a67000-00a68000 rw-p 00002000 fd:00 1064652    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/thread.so
00ac4000-00ac7000 r-xp 00000000 fd:00 1064651    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/digest.so
00ac7000-00ac8000 rw-p 00002000 fd:00 1064651    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/digest.so
00aec000-00af8000 r-xp 00000000 fd:00 2903600    /lib/libnss_files-2.12.so
00af8000-00af9000 r--p 0000b000 fd:00 2903600    /lib/libnss_files-2.12.so
00af9000-00afa000 rw-p 0000c000 fd:00 2903600    /lib/libnss_files-2.12.so
00b1b000-00b2d000 r-xp 00000000 fd:00 2522037    /usr/local/rvm/gems/ruby-2.1.0/gems/redcarpet-3.3.4/lib/redcarpet.so
00b2d000-00b2e000 rw-p 00012000 fd:00 2522037    /usr/local/rvm/gems/ruby-2.1.0/gems/redcarpet-3.3.4/lib/redcarpet.so
00b34000-00d6c000 r-xp 00000000 fd:00 689486     /usr/local/rvm/rubies/ruby-2.1.0/lib/libruby.so.2.1.0
00d6c000-00d71000 rw-p 00238000 fd:00 689486     /usr/local/rvm/rubies/ruby-2.1.0/lib/libruby.so.2.1.0
00d71000-00d86000 rw-p 00000000 00:00 0
00df9000-00e06000 r-xp 00000000 fd:00 1064632    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/zlib.so
00e06000-00e07000 rw-p 0000d000 fd:00 1064632    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/zlib.so
00e18000-00e1e000 r-xp 00000000 fd:00 1064555    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/stringio.so
00e1e000-00e1f000 rw-p 00006000 fd:00 1064555    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/stringio.so
00e9b000-00e9d000 r-xp 00000000 fd:00 1064631    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/trans/transdb.so
00e9d000-00e9e000 rw-p 00001000 fd:00 1064631    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/trans/transdb.so
00f12000-00f15000 r-xp 00000000 fd:00 1064659    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/io/console.so
00f15000-00f16000 rw-p 00002000 fd:00 1064659    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/io/console.so
00f21000-00f22000 r-xp 00000000 fd:00 1064610    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/utf_16le.so
00f22000-00f23000 rw-p 00000000 fd:00 1064610    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/enc/utf_16le.so
00f73000-00f98000 r-xp 00000000 fd:00 1064573    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/socket.so
00f98000-00f99000 rw-p 00024000 fd:00 1064573    /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/i686-linux/socket.so
00f99000-0115a000 r-xp 00000000 fd:00 1457183    /usr/local/rvm/gems/ruby-2.1.0/gems/nokogiri-1.6.8.1/lib/nokogiri/nokogiri.so
0115a000-01161000 rw-p 001c1000 fd:00 1457183    /usr/local/rvm/gems/ruby-2.1.0/gems/nokogiri-1.6.8.1/lib/nokogiri/nokogiri.so
01161000-01162000 rw-p 00000000 00:00 0
01162000-017f2000 r-xp 00000000 fd:00 1463277    /usr/local/rvm/gems/ruby-2.1.0/gems/therubyracer-0.12.3/lib/v8/init.so
017f2000-017f6000 rw-p 0068f000 fd:00 1463277    /usr/local/rvm/gems/ruby-2.1.0/gems/therubyracer-0.12.3/lib/v8/init.so
017f6000-017f8000 rw-p 00000000 00:00 0
026ca000-02710000 r-xp 00000000 fd:00 548787     /usr/lib/libjpeg.so.62.0.0
02710000-02711000 rw-p 00046000 fd:00 548787     /usr/lib/libjpeg.so.62.0.0
02711000-02721000 rw-p 00000000 00:00 0
02750000-02759000 r-xp 00000000 fd:00 552841     /usr/lib/libltdl.so.7.2.1
02759000-0275a000 rw-p 00008000 fd:00 552841     /usr/lib/libltdl.so.7.2.1
027f8000-02851000 r-xp 00000000 fd:00 547938     /usr/lib/libXt.so.6.0.0
02851000-02855000 rw-p 00058000 fd:00 547938     /usr/lib/libXt.so.6.0.0
028c3000-02ad8000 r-xp 00000000 fd:00 549008     /usr/lib/libMagickCore.so.5.0.0
02ad8000-02b28000 rw-p 00214000 fd:00 549008     /usr/lib/libMagickCore.so.5.0.0
02b28000-02b40000 rw-p 00000000 00:00 0
0332a000-0357a000 r-xp 00000000 fd:00 1315237    /usr/lib/mysql/libmysqlclient.so.18.0.0
0357a000-035f1000 rw-p 00250000 fd:00 1315237    /usr/lib/mysql/libmysqlclient.so.18.0.0
035f1000-035f4000 rw-p 00000000 00:00 0
057e2000-05918000 r-xp 00000000 fd:00 548438     /usr/lib/libX11.so.6.3.0
05918000-0591b000 rw-p 00135000 fd:00 548438     /usr/lib/libX11.so.6.3.0
0591b000-0591c000 rw-p 00000000 00:00 0
06af5000-06ca6000 r-xp 00000000 fd:00 548735     /usr/lib/libcrypto.so.1.0.1e
06ca6000-06cb6000 r--p 001b0000 fd:00 548735     /usr/lib/libcrypto.so.1.0.1e
06cb6000-06cbd000 rw-p 001c0000 fd:00 548735     /usr/lib/libcrypto.so.1.0.1e
06cbd000-06cc0000 rw-p 00000000 00:00 0
07e5c000-07e92000 r-xp 00000000 fd:00 549004     /usr/lib/liblcms.so.1.0.19
07e92000-07e94000 rw-p 00035000 fd:00 549004     /usr/lib/liblcms.so.1.0.19
07e94000-07e96000 rw-p 00000000 00:00 0
07e98000-07ef8000 r-xp 00000000 fd:00 551134     /usr/lib/libtiff.so.3.9.4
07ef8000-07efa000 rw-p 00060000 fd:00 551134     /usr/lib/libtiff.so.3.9.4
07f38000-08019000 r-xp 00000000 fd:00 548600     /usr/lib/libstdc++.so.6.0.13
08019000-0801d000 r--p 000e0000 fd:00 548600     /usr/lib/libstdc++.so.6.0.13
0801d000-0801f000 rw-p 000e4000 fd:00 548600     /usr/lib/libstdc++.so.6.0.13
0801f000-08025000 rw-p 00000000 00:00 0
08048000-08049000 r-xp 00000000 fd:00 689373     /usr/local/rvm/rubies/ruby-2.1.0/bin/ruby
08049000-0804a000 rw-p 00000000 fd:00 689373     /usr/local/rvm/rubies/ruby-2.1.0/bin/ruby
09f5f000-1087c000 rw-p 00000000 00:00 0          [heap]
b6a00000-b6a21000 rw-p 00000000 00:00 0
b6a21000-b6b00000 ---p 00000000 00:00 0
b6b48000-b6b49000 ---p 00000000 00:00 0
b6b49000-b7549000 rw-p 00000000 00:00 0
b7549000-b7550000 r--s 00000000 fd:00 820309     /usr/lib/gconv/gconv-modules.cache
b7550000-b7551000 ---p 00000000 00:00 0
b7551000-b75d5000 rw-p 00000000 00:00 0
b75d5000-b77d5000 r--p 00000000 fd:00 820458     /usr/lib/locale/locale-archive
b77d5000-b77d8000 rw-p 00000000 00:00 0
b77f3000-b77f5000 rw-p 00000000 00:00 0
bf7c3000-bf8d8000 rw-p 00000000 00:00 0          [stack]

>

My environment is this 
Environment:
  Redmine version                3.2.1.stable
  Ruby version                   2.1.0-p0 (2013-12-25) [i686-linux]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.4
  Git                            1.7.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.1.10
  additionals                    2.0.0
  advanced_roadmap               0.10.1
  clipboard_image_paste          1.10
  computed_custom_field          0.0.8
  custom_menu                    1.7.0
  export_docx                    1.2.2
  extra_queries                  2.2.0
  favorite_locations             0.0.1
  global_roles                   2.1.0
  mega_calendar                  1.3.8
  pdf_export                     0.1
  progressive_projects_list      2.0.1
  project_colors                 0.0.3
  projects_show                  0.0.3
  redmine__select2               1.0.5
  redmine_banner                 0.1.2
  redmine_bootstrap_kit          0.2-devel
  redmine_checklists             3.1.4
  redmine_ckeditor               1.1.5
  redmine_code_review            0.7.0
  redmine_custom_css             0.1.6
  redmine_custom_workflows       0.1.6
  redmine_dashboard              2.5.0
  redmine_default_custom_query   1.2.0
  redmine_diff_email             0.3.0
  redmine_dmsf                   1.5.6
  redmine_drawio                 0.6.0
  redmine_dynamic_file_link      0.0.1
  redmine_email_images           0.1.1
  redmine_entity_generator       2016
  redmine_extended_watchers      1.0.5
  redmine_favourite_projects     0.9
  redmine_googlesss              0.0.2
  redmine_info_tab               1.1.0
  redmine_issue_badge            0.0.3
  redmine_issue_history          1.0.0
  redmine_issue_history_filter   0.0.1
  redmine_issue_icons            1.0.0
  redmine_issue_templates        0.1.7
  redmine_issue_todo_lists       1.1.1
  redmine_lightbox2              0.2.7
  redmine_list_of_roles_members  0.1.0
  redmine_mail_reminder          3.0.0.0001
  redmine_materials              0.1.4
  redmine_meeting_room_calendar  3.0.0
  redmine_my_page                0.1.10
  redmine_people                 1.2.0
  redmine_per_project_formatting 0.0.4
  redmine_print_issue            1.0.2
  redmine_scheduling_poll        1.4.1
  redmine_serial_number_field    0.9.0
  redmine_silencer               0.4.1
  redmine_startpage              0.1.0
  redmine_stats                  0.0.1
  redmine_subtask_overview_enhanced 0.1.0
  redmine_theme_changer          0.2.0
  redmine_wiki_extensions        0.7.0
  redmine_workflow_enhancements  0.5.0
  redmine_workflow_hidden_fields 0.3.0
  redmine_xlsx_format_issue_exporter 0.1.3
  redmine_xmpp_muc_notifications 1.0.0
  redmine_zenedit                0.0.2
  release_logs                   1.0.0
  rm_user_mentions               1.0.0
  scrum                          0.16.2
  unread_issues                  2.1.0
  usability                      2.1.2
  view_customize                 1.1.4
  welcome_picture                1.0.0
  wiking                         1.0.0b

**Comment by arBmind** [comment]
you have a lot of Redmine Extensions please try hourglass without those. I would guess one of them creates a conflict.

**Comment by mauriziotallarico** [comment]
I see. Thanks, i'll try and let you know if a plugin creates trouble.
