### ISSUE TITLE
How to migrate from previous timetracker plugin?

### ISSUE THREAD

**Issue by xstable** [hicknhack-software/redmine_hourglass#49]
Hi, Ive currently upgraded to Redmine 3.4.2-stable.
I've used your redmine_timetracker plugin before and still have installed it to 0.10.6.

Seems to works (with some Bugs), but I wan't to swtich to your new Hourglass-Plugin.
So my question: Is there a way to migrate, to keep the tracked times made with previous plugin even in hourglass?

**Comment by arBmind** [comment]
Yes, see the [Migration Guide](https://github.com/hicknhack-software/redmine_hourglass/wiki/Migration-Guide)

**Comment by jume-dev** [comment]
I don't want to sound mean or anything, but i am curious if the readme is bad and we need to improve it, so let me ask you: Didn't you see the bold, italic paragraph in the first part of the readme? Should we make that like bigger or something?

**Comment by xstable** [comment]
I was in "scan-mode" and only searching for the Headline "Migrate". So maybe instead of just bold it in the pre-text, add an section "Migration" to describe it.
But anyway, now I see where I can found the info.... good work ^^
Thanks a lot

**Comment by jume-dev** [comment]
thanks for your input, fixed the readme
