### ISSUE TITLE
Hourglass-App (Android) find no projects

### ISSUE THREAD

**Issue by xstable** [hicknhack-software/redmine_hourglass#51]
I have many Projects at my redmine-server.
I've configured the connection with the Redmine-Api, and "seems" to connect. But there is only a message: No content available.

**Comment by jume-dev** [comment]
Same as in #50, please check if the plugin is enabled on your project and you have set the appropriate access rights.

**Comment by xstable** [comment]
Ok, I've missed to enabled hourglass for projects - is there a way to enable it for all existing projects at once?
This way it works. (I've another Problem, that I can stop a timetracker via app, but not in the Webgui... but better we discuss this in the other ticket, because is no app-bug).

**BTW:** Did you have a suggestion, how to delete unneeded Connection in the App? I only see the "+" Button for adding a new connection, but not a way to delete an old one.

**Comment by jume-dev** [comment]
No, the way redmine works is, that you need to enable it for each project. But i think you can set it on default for new projects atleast, but i am not sure about that, don't pin me to it.

The app handles stuff a bit differently than the web view, it's possible that there a slightly inconsistencies. Check your permissions, maybe you are missing something there. Other then that, let's discuss in an other issue. I am gonna close this now.

(i just talked to our app dev guy, he said you can swipe left on an entry in the connection overview to see a menu with deleting and changing)
