### ISSUE TITLE
Cannot stop timer

### ISSUE THREAD

**Issue by ctyler2621** [hicknhack-software/redmine_hourglass#57]
Started timer without issue, but cannot stop it now.

From the logs...
Started DELETE "/hourglass/time_trackers/current/stop" for 69.71.12.18 at 2017-10-12 17:33:16 +0000
Processing by Hourglass::TimeTrackersController#stop as */*
  Parameters: {"id"=>"current"}
  Current user: ctyler (id=5)
Completed 403 Forbidden in 23ms (Views: 0.5ms | ActiveRecord: 5.7ms)

Environment:
  Redmine version                3.2.6.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Mercurial                      3.1.2
  Bazaar                         2.7.0
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  redmine_hourglass              1.0.0
  redmine_slack                  0.2

User has full permissions for all hourglass functions in roles/permissions. I have tried to uninstall/reinstall to no avail. Not sure where to go from here, any assistance is appreciated.

**Comment by ctyler2621** [comment]
Disregard. It's working now. Not sure what I did to "fix" it but no more errors in the logs and I can now stop timers.

**Comment by jume-dev** [comment]
Alright, glad i could help ;)

If by any chance you find out, what the problem was, let me know. I guess it was some stuff like project had the plugin enabled or weird permission interception, hard to track such stuff :(
