### ISSUE TITLE
Manual Timelog are not shown in the overview - but in the Redmine-Internal Tracker

### ISSUE THREAD

**Issue by xstable** [hicknhack-software/redmine_hourglass#59]
1. Open an Ticket,
2. Manually add an Timebooking:  Press the Icon "Aufwand buchen" (don't know how the english Button is named, it link  to: /issues/886/time_entries/new)
3) Enter your data and save.

**Result:** 
The saved time is not visible in hourglass time_bookings nor time_logs.

**Should be:** 
Would be nice, if hourglas save all entries in the "default-redmine-time-log-table".

**Comment by jume-dev** [comment]
This is already tracked in #14
