### ISSUE TITLE
Modifying or entering time entries from the past - error

### ISSUE THREAD

**Issue by ctarara** [hicknhack-software/redmine_hourglass#63]
It seems that when you go in "time bookings" and you want to modify or introduce time entries that starts in the past it does not permit you to do so (for existing time entries when you operate on the "data start", for the new entries - it does not allow you at all - it gives a message with Overlapp... (there are no other time entries to cover that period).
It should allow this in order to fix some mistakes.

**Comment by mstarke** [comment]
This issue only occurs on the Bookings not the Trackings edit form. It seems that the date calculation is wrong on the Bookings form.

**Comment by arBmind** [comment]
seems fixed.
