### ISSUE TITLE
Interface language

### ISSUE THREAD

**Issue by alevashov** [hicknhack-software/redmine_hourglass#66]
Hi

I have installed your great plugin on my Redmine (information is below) and experience a weird problem - the interface language of Hourglass is wrong and different from the rest of Redmine.

I have it set to be English on both user and general settings default display language, but Hourglass uses Russian for some reason.

See screenshot - http://easycaptures.com/fs/uploaded/1037/6326643683.png

My Redmine information:
Environment:
  Redmine version                3.4.4.stable.17186
  Ruby version                   2.4.1-p111 (2017-03-22) [i686-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.5
  redmine_checklists             3.1.10
  redmine_hourglass              1.0.0

**Comment by alevashov** [comment]
Update: the interface language went back to normal (English) on Redmine theme change, even if after I've changed back to the theme where it has displayed wrongly.

**Comment by alevashov** [comment]
Update 2: It is even more weird, but the issue returned after some time and changing the theme doesn't help anymore

**Comment by alevashov** [comment]
Update 3. Interface language normalizes after Nginx restart, but then after some time becomes wrong again.

**Comment by jume-dev** [comment]
woah, that's strange, i initially had absolutely no idea what could have caused this. But it was easy to found. The guy submitting the russian locale made a copy and paste mistake and i didn't catch it. Gonna be fixed in a few minutes.
Thanks for reporting this bug ❤️

**Comment by alevashov** [comment]
Great, @jume-dev 

Looking forward to the fix
Thanks a lot for taking over from redmine_time_tracker and creating and supporting this plugin
