### ISSUE TITLE
Redmine: Error 500

### ISSUE THREAD

**Issue by nextechg** [hicknhack-software/redmine_hourglass#68]
Getting the error Redmine: Error 500 while accessing /hourglass/ui

http://xxxxx.com/hourglass/ui

We are running:
Environment:
  Redmine version                3.4.4.stable.17194
  Ruby version                   2.4.1-p111 (2017-03-22) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.4.0
  easy_instant_messages          2016
  redmine_agile                  1.4.5
  redmine_checklists             3.1.10
  redmine_hourglass              1.0.0
  redmine_lightbox2              0.4.3
  usability                      2.3.2

Error log

     /var/www/html/redmine/plugins/redmine_hourglass/app/controllers/concerns/date_time_parsing.rb:29:in `date_time_strings_map'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/abstract_controller/helpers.rb:67:in `date_time_strings_map'
/var/www/html/redmine/plugins/redmine_hourglass/app/views/hourglass_ui/layouts/_hourglass.slim:11:in `block in _plugins_redmine_hourglass_app_views_hourglass_ui_layouts__hourglass_slim___1357784476999895425_70158746635340'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:38:in `capture'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:152:in `content_for'
/var/www/html/redmine/plugins/redmine_hourglass/app/views/hourglass_ui/layouts/_hourglass.slim:1:in `_plugins_redmine_hourglass_app_views_hourglass_ui_layouts__hourglass_slim___1357784476999895425_70158746635340'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/template.rb:145:in `block in render'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/template.rb:333:in `instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/template.rb:143:in `render'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:309:in `render'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:51:in `render_partial'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/helpers/rendering_helper.rb:30:in `render'
/var/www/html/redmine/plugins/redmine_hourglass/app/views/hourglass_ui/index.slim:1:in `_plugins_redmine_hourglass_app_views_hourglass_ui_index_slim___1207177163047869516_70158749420700'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/template.rb:145:in `block in render'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/template.rb:333:in `instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/template.rb:143:in `render'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:14:in `render'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:46:in `render_template'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:27:in `render'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/rendering.rb:100:in `_render_template'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/rendering.rb:83:in `render_to_body'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/abstract_controller/rendering.rb:25:in `render'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:16:in `render'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:43:in `render'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:198:in `process_action'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/var/www/html/redmine/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:312:in `block in halting'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:497:in `block in around'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:137:in `process'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionview-4.2.8/lib/action_view/rendering.rb:30:in `process'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal.rb:196:in `dispatch'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_controller/metal.rb:237:in `block in action'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/etag.rb:24:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/conditionalget.rb:25:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/flash.rb:260:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225:in `context'
/usr/local/rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/query_cache.rb:36:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `block in call'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:26:in `tagged'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `tagged'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-4.2.8/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/static.rb:120:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/usr/local/rvm/gems/ruby-2.4.1/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/usr/local/rvm/gems/ruby-2.4.1/gems/passenger-5.2.0/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/local/rvm/gems/ruby-2.4.1/gems/passenger-5.2.0/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/usr/local/rvm/gems/ruby-2.4.1/gems/passenger-5.2.0/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/local/rvm/gems/ruby-2.4.1/gems/passenger-5.2.0/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/local/rvm/gems/ruby-2.4.1/gems/passenger-5.2.0/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by jume-dev** [comment]
I am sorry, but you only posted the stacktrace and no actual exception message. i have no idea what the problem could be

**Comment by nextechg** [comment]
Sorry. We are new to redmine. Can you please let us know how to get the stacktrace?

Thanks

**Comment by jume-dev** [comment]
You misunderstood me here. What you posted (the long stuff) is the stacktrace, but there is missing the first line which would say something like: "Exception occured in ". That's what i meant with exception message. Please check your logs, if you find that line, otherwise i am afraid i can't help you

**Comment by nextechg** [comment]
is this is the exception?

undefined method `flatten' for "translation missing: en-US.date.abbr_month_names":String 

Thanks

**Comment by jume-dev** [comment]
Yes, it is, thanks.

It looks like this is a problem with your language. As a temporary work around try setting your language to plain english instead of english (US).

Otherwise there isn't much we can do here. It looks like one of your plugin introduced en-US in your redmine but didn't provide proper month names.

Sadly there is nothing we can do here from our side. If you are familiar with ruby you can work through this and try to adjust your redmine to enable this: https://github.com/svenfuchs/i18n/wiki/Fallbacks
