### ISSUE TITLE
Server Error 500 on api issue search

### ISSUE THREAD

**Issue by danaivehr** [hicknhack-software/redmine_hourglass#72]
Thank you for your great app!

Please fix an issue with completion contoller:

When i use iOS Hourglass app for your plugin and trying to find an issue by text, i get Error 500

```
ERROR:  operator does not exist: integer ~~* integer
LINE 1: ...lass')) AND (("issues"."id" = 77 OR "issues"."id" ILIKE 77) ...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts
```

It seems to be a problem in  hourglass_completion_controller.rb:

```
    issues = Issue.visible.joins(:project).where(Project.allowed_to_one_of_condition User.current, Hourglass::AccessControl.permissions_from_action(con
        issue_arel[:id].eq(params[:term].to_i)
            .or(issue_arel[:id].matches("%#{params[:term]}%"))
            .or(issue_arel[:subject].matches("%#{params[:term]}%"))
```

in issue_arel[:id].matches("%#{params[:term]}%")

As far as i can see, there is implicit type conversion for term to int, since ":id" is integer, but ILIKE argument need to be string.

I have no knowledge to fix it (tryed "%#{params[:term].to_s}%", but it is converted to integer nevertheless), so i just commented it out for now.

My environment:
Redmine 3.4.2
Ruby version                   2.3.4-p301 (2017-03-30) [x86_64-linux]
Rails version                  4.2.8
Database adapter               PostgreSQL 9.6.2
Ubuntu Trusty

**Comment by strfry** [comment]
Confirmed. Will look into fixing this tomorrow.

**Comment by strfry** [comment]
Should be fixed now in next-version branch
