### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by M0d3rn15t** [hicknhack-software/redmine_hourglass#73]
Having installed the plugin, every thing looks fine - I can configure the plugin and the 'Start Time Tracker' seems to appear in the correct places, however, when the button is clicked I get a page not found error (404), regardless of whether or not the module is enabled in the project.

The attempted link is http://myredmine.com/hourglass/time_trackers/start.

I suspect, maybe a relative path issue with the second rake execution....

rake redmine:plugins:assets RAILS_ENV=production RAILS_RELATIVE_URL_ROOT=/redmine

My Redmine server is currently working well in all other respects. 

Server is CentOS7 with Plesk Onyx 17.x

Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.3.6-p384 (2017-12-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.5
  redmine_checklists             3.1.10
  redmine_cms                    1.1.0
  redmine_contacts               4.1.2
  redmine_contacts_helpdesk      3.0.9
  redmine_contacts_invoices      4.1.6
  redmine_crm_mailchimp          1.0.2
  redmine_dmsf                   1.6.0
  redmine_favorite_projects      2.0.3
  redmine_finance                2.1.3
  redmine_hourglass              1.0.0
  redmine_people                 1.3.2
  redmine_products               2.0.4
  redmine_questions              0.0.7
  redmine_zenedit                0.0.2
  redmineup_tags                 2.0.1

**Comment by jume-dev** [comment]
mhm, and what would be the correct link?

Looks definitly like a path issue for me

**Comment by M0d3rn15t** [comment]
In Plesk, Redmine is stored in the virtual hosts file structure.

/var/www/vhosts/mydomain.co.uk/httpdocs/redmine

I am not sure if this is an issue with the db migration, and the relative path rake, or a deeper path issue.

That said, the rake migration resulted in success and a repeat of the command implies that paths are handled correctly.

`/opt/plesk/ruby/2.3.6/bin/ruby -I/var/www/vhosts/projexz.co.uk/httpdocs/redmine/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.7.1/lib:/var/www/vhosts/projexz.co.uk/httpdocs/redmine/vendor/bundle/ruby/2.3.0/gems/rspec-support-3.7.1/lib /var/www/vhosts/projexz.co.uk/httpdocs/redmine/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.7.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
No examples found.`

Similarly, the asset rake, 
redmine:plugins:assets RAILS_ENV=production RAILS_RELATIVE_URL_ROOT=/redmine

results in, the same thing.

I'd be grateful for any pointers as to how to get this plugin working.

The server is currently working but has occasional path/access fumbles.

![ashampoo_snap_2018 03 15_12h24m59s_004_](https://user-images.githubusercontent.com/36712345/37463124-2834c1ce-284c-11e8-9bdd-35e33f0e6fb6.png)

**Comment by M0d3rn15t** [comment]
Ooops! The rake results above were while the server was in development.

The following results were in production.
'Migrating redmine_agile (Redmine Agile plugin (PRO version))...
Migrating redmine_checklists (Redmine Checklists plugin (PRO version))...
Migrating redmine_cms (Redmine CMS plugin)...
Migrating redmine_contacts (Redmine CRM plugin (PRO version))...
Migrating redmine_contacts_helpdesk (Redmine Helpdesk plugin (PRO version))...
Migrating redmine_contacts_invoices (Redmine Invoices plugin (PRO version))...
Migrating redmine_crm_mailchimp (RedmineUP Mailchimp plugin)...
Migrating redmine_dmsf (DMSF)...
Migrating redmine_drawio (Redmine Drawio plugin)...
Migrating redmine_favorite_projects (Redmine Favorite Projects plugin)...
Migrating redmine_finance (Redmine Finance plugin (PRO version))...
Migrating redmine_hourglass (Hourglass)...
Migrating redmine_people (Redmine People plugin (PRO version))...
Migrating redmine_products (Redmine Products plugin (PRO version))...
Migrating redmine_questions (Redmine Q&A plugin)...
Migrating redmine_zenedit (Redmine Zen Edit plugin)...
Migrating redmineup_tags (Redmine Tags plugin (Light version))...
/var/www/vhosts/projexz.co.uk/httpdocs/redmine/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::VCF
/var/www/vhosts/projexz.co.uk/httpdocs/redmine/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of VCF was here'

The result of the asset rake is
'/var/www/vhosts/projexz.co.uk/httpdocs/redmine/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::VCF
/var/www/vhosts/projexz.co.uk/httpdocs/redmine/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of VCF was here'

**Comment by M0d3rn15t** [comment]
Thanks for closing without informing me.

Your plugin will now been removed from our site.

**Comment by mstarke** [comment]
@M0d3rn15t didn't you close this by yourself?
![screen shot 2018-03-15 at 14 25 02](https://user-images.githubusercontent.com/58428/37465886-a8f5bde4-285c-11e8-8551-550f87c312d8.png)

**Comment by M0d3rn15t** [comment]
Not intentionally, but the website has crashed a couple of times while I have been updating information.

Does the close button not have an "are you sure" dialogue?

**Comment by jume-dev** [comment]
Careful, the rake task parameter says RAILS_RELATIVE_URL_ROOT. This doesnt mean the actual directory where redmine lays, but the website url.

Is you the main url to your redmine instance your-domain.de/redmine or your-domain.de?

if the second, you dont need that parameter

**Comment by M0d3rn15t** [comment]
I have tried it both with and without the relative path, same result.

I tried it without first as the my url is projexz.co.uk.

My link to production.log appears to be broken, for some reason it is not updating.
