### ISSUE TITLE
install fails with: Sprockets::FileNotFound: couldn't find file 'swagger-ui/lib/jquery.slideto.min'

### ISSUE THREAD

**Issue by okionka** [hicknhack-software/redmine_hourglass#75]
rake redmine:plugins:assets RAILS_ENV=production
(in /usr/src/redmine)
rake aborted!
Sprockets::FileNotFound: couldn't find file 'swagger-ui/lib/jquery.slideto.min' with type 'application/javascript'
Checked in these paths:
:
:

I'm using a dockerized Redmine from https://hub.docker.com/_/redmine/
Environment:
  Redmine version                3.4.5.stable
  Ruby version                   2.4.4-p296 (2018-03-28) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2

I did following:

1. Bring docker containers (redmine + mysql) up and running, did the initial redmine setup (admin password, applied default settings)
2. logon to redmine container: docker exec -ti redmine_app_1 gosu redmine bash
3. cloned git repo by: cd plugins; git clone https://github.com/hicknhack-software/redmine_hourglass.git
4, dependencies installation by "bundle install" failed due missing developement tools.
5. installed missing OS packages as root by: apt-get update; apt-get install gcc make g++
6. "bundle install" were now successful.
7. executed successful: rake redmine:plugins:migrate RAILS_ENV=production
8. executed unsuccessful: rake redmine:plugins:assets RAILS_ENV=production
9. recieved this " Sprockets::FileNotFound"-error.

any hints for installing this plugin?

**Comment by jume-dev** [comment]
Sadly i can't check myself, but maybe look at the swagger-ui gem version, maybe it's corrupted and is missing the mentioned file.

**Comment by AlexeyGal** [comment]
cd ~/
git clone https://github.com/swagger-api/swagger-ui.git 
cd ./swagger-ui
git checkout v2.2.10
cp -R ./dist /var/www/redmine/plugins/redmine_hourglass/vendor/assets/javascripts
cd /var/www/redmine/plugins/redmine_hourglass/vendor/assets/javascripts
mv ./dist ./swagger-ui
-----------------------------------------------
cd /var/www/redmine
rake redmine:plugins:migrate RAILS_ENV=production
rake redmine:plugins:assets RAILS_ENV=production
-----------------------------------------------
rake tmp:cache:clear RAILS_ENV=production
rake tmp:sessions:clear RAILS_ENV=production
-----------------------------------------------
sudo service apache2 restart
sudo service mysql restart
-----------------------------------------------
![2018-06-14_14-38-32](https://user-images.githubusercontent.com/3528353/41410101-02f645fe-6fe1-11e8-93e8-5a62be760fd2.png)

**Comment by okionka** [comment]
Thanks, your way to copy the swagger-ui sources over to the hourglasss sources works in  combination with the steps above.  Finally the hourglass is working in an dockerized environment.

**Comment by hameno** [comment]
I have the same error on Redmine 3.3, could you please adjust the installation guide / fix the package

**Comment by okionka** [comment]
1. Bring docker containers (redmine + mysql) up and running, did the initial redmine setup (admin password, applied default settings)
2. dependencies installation by "bundle install" failed due missing developement tools. logon to redmine container as root by:

    docker exec -ti redmine_app_1 bash

3. Install missing OS packages for developement in redmine-container:

    apt-get update; apt-get install gcc make g++

4. logon to redmine container as user redmine:

    docker exec -ti redmine_app_1 gosu redmine bash

5. cloned git repos (Hourglass and merge with swagger) in redmine-container by:

    cd plugins; git clone https://github.com/hicknhack-software/redmine_hourglass.git
    cd ~/; git clone https://github.com/swagger-api/swagger-ui.git; cd ./swagger-ui; git checkout v2.2.10
    cp -R ./dist /usr/src/redmine/plugins/redmine_hourglass/vendor/assets/javascripts
    cd /usr/src/redmine/plugins/redmine_hourglass/vendor/assets/javascripts
    mv ./dist ./swagger-ui
    cd /usr/src/redmine
    rake redmine:plugins:migrate RAILS_ENV=production
    rake redmine:plugins:assets RAILS_ENV=production
    rake tmp:cache:clear RAILS_ENV=production
    rake tmp:sessions:clear RAILS_ENV=production

6. finally, restart redmine and DB container:

    docker-compose restart
