### ISSUE TITLE
Tags for new Versions

### ISSUE THREAD

**Issue by xstable** [hicknhack-software/redmine_hourglass#76]
Could you please create Tags here on GitHub if you release new Versions. 
It would make it easier to see if an update is available.

What is the current Version?

**Comment by jume-dev** [comment]
You are totally right. Our version management in this repo is bad, really really bad. So technically this one is still version 1.0.0, but actually in a minor version somewhere around 1.0.7 actually i suppose.

Someone should fix this some day.

**Comment by arBmind** [comment]
Organized the repository… proper 1.0 release is out. Next is 1.1
