### ISSUE TITLE
Support filters in API calls

### ISSUE THREAD

**Issue by martinhey** [hicknhack-software/redmine_hourglass#93]
Currently the API doesn't support filters and sort as standard redmine services do.
Please provide support to filter for date / date ranges, users and projects

e.g.
/time_bookings.json?start=<>2018-10-01|2018-10-30

**Comment by arBmind** [comment]
It might be helpful to switch to GraphQL and allow less API calls.

**Comment by dmartingit** [comment]
The Api does support filters:
e.g.

> /time_bookings.json?date=><2018-10-01|2018-10-30
> /time_bookings.json?project_id=1
> /time_logs.json?user_id=1

**Comment by martinhey** [comment]
So the filter parameter for "start" and "stop" on time bookings is "date"?
Where can I find a list of valid filter parameters and which field they apply on?

**Comment by dmartingit** [comment]
Currently each filter available in the ui is also available in the api.
For time logs:
https://github.com/hicknhack-software/redmine_hourglass/blob/68124c3882eb0945bc9302ffb1f3fff4bf430b60/app/models/hourglass/time_log_query.rb#L23-L26

For time bookings and time tracker:
https://github.com/hicknhack-software/redmine_hourglass/blob/68124c3882eb0945bc9302ffb1f3fff4bf430b60/app/models/hourglass/time_tracker_query.rb#L23-L33

**Comment by martinhey** [comment]
First of all - thanks for the hints. So there are filters, but theres almost no documentation - except of the code itself. So it's hard to understand what field parameters work, what are possible parameters and which fields they apply to.

Regarding to my tests on time bookings, the filter for the date field applies to the start date of the time booking.

So maybe I should rename the issue to "Create a wiki page of possible filter criterias and the intended behavior".

**Comment by arBmind** [comment]
I'm glad we could help you.

The virtual date column for filtering is always the date of start:
https://github.com/hicknhack-software/redmine_hourglass/blob/68124c3882eb0945bc9302ffb1f3fff4bf430b60/app/models/concerns/hourglass/query_base.rb#L98-L100

Contributions are always appreciated, but please create a new issue instead of redirecting existing issues.
