### ISSUE TITLE
Don't show  start time tracker when module is not enabled

### ISSUE THREAD

**Issue by hameno** [hicknhack-software/redmine_hourglass#95]
Please don't show the "start time tracker" entry on issues when the module is not even enabled. This will cause errors when users try to use this link.
Also, please get rid of the `<li></li>` in the issue description html.

**Comment by hameno** [comment]
@arBmind Any update?

**Comment by arBmind** [comment]
@hameno We are quite busy right now.

Sorry, that these issues will collect a bit of dust, before a developer has time to fix them.
